/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Categories extends CategoriesBase
{
    public Categories()
    {
        this((BusObjectConfig)null);
    }

    public Categories(BusObjectConfig config)
    {
        super(config);
    }

}
