/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class CustomerDemographics extends CustomerDemographicsBase
{
    public CustomerDemographics()
    {
        this((BusObjectConfig)null);
    }

    public CustomerDemographics(BusObjectConfig config)
    {
        super(config);
    }

}
