/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class CustomerCustomerDemo extends CustomerCustomerDemoBase
{
    public CustomerCustomerDemo()
    {
        this((BusObjectConfig)null);
    }

    public CustomerCustomerDemo(BusObjectConfig config)
    {
        super(config);
    }

}
