/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class EmployeeTerritories extends EmployeeTerritoriesBase
{
    public EmployeeTerritories()
    {
        this((BusObjectConfig)null);
    }

    public EmployeeTerritories(BusObjectConfig config)
    {
        super(config);
    }

}
