/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Orders extends OrdersBase
{
    public Orders()
    {
        this((BusObjectConfig)null);
    }

    public Orders(BusObjectConfig config)
    {
        super(config);
    }

}
