/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Order_x0020_Details extends Order_x0020_DetailsBase
{
    public Order_x0020_Details()
    {
        this((BusObjectConfig)null);
    }

    public Order_x0020_Details(BusObjectConfig config)
    {
        super(config);
    }

}
