/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Region extends RegionBase
{
    public Region()
    {
        this((BusObjectConfig)null);
    }

    public Region(BusObjectConfig config)
    {
        super(config);
    }

}
