/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_FK;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class SuppliersBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SupplierID = "SupplierID";
    public final static String ATTR_CompanyName = "CompanyName";
    public final static String ATTR_ContactName = "ContactName";
    public final static String ATTR_ContactTitle = "ContactTitle";
    public final static String ATTR_Address = "Address";
    public final static String ATTR_City = "City";
    public final static String ATTR_Region = "Region";
    public final static String ATTR_PostalCode = "PostalCode";
    public final static String ATTR_Country = "Country";
    public final static String ATTR_Phone = "Phone";
    public final static String ATTR_Fax = "Fax";
    public final static String ATTR_HomePage = "HomePage";
    private final static String REL_ProductsObjects = "FK:Suppliers[SupplierID]:Products[SupplierID]";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(Suppliers.class);
            s_classInfo.setTableName("Suppliers");
            s_classInfo.setUIDElements(new String[]{ATTR_SupplierID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SupplierID);
                ai.setJavaName("SupplierID");
                ai.setColumnName("SupplierID");
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SupplierID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompanyName);
                ai.setJavaName("CompanyName");
                ai.setColumnName("CompanyName");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompanyName);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ContactName);
                ai.setJavaName("ContactName");
                ai.setColumnName("ContactName");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ContactName);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ContactTitle);
                ai.setJavaName("ContactTitle");
                ai.setColumnName("ContactTitle");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ContactTitle);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Address);
                ai.setJavaName("Address");
                ai.setColumnName("Address");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Address);
                v.setMaxLength(60);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_City);
                ai.setJavaName("City");
                ai.setColumnName("City");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_City);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Region);
                ai.setJavaName("Region");
                ai.setColumnName("Region");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Region);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PostalCode);
                ai.setJavaName("PostalCode");
                ai.setColumnName("PostalCode");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PostalCode);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Country);
                ai.setJavaName("Country");
                ai.setColumnName("Country");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Country);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Phone);
                ai.setJavaName("Phone");
                ai.setColumnName("Phone");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Phone);
                v.setMaxLength(24);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Fax);
                ai.setJavaName("Fax");
                ai.setColumnName("Fax");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Fax);
                v.setMaxLength(24);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_HomePage);
                ai.setJavaName("HomePage");
                ai.setColumnName("HomePage");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_HomePage);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                // relation ProductsObjects (FK:Suppliers[SupplierID]:Products[SupplierID])
                RelationInfo_FK ri = new RelationInfo_FK(REL_ProductsObjects);
                ri.setName("ProductsObjects");
                ri.setLocalAttributes(new String[]{"SupplierID"});
                ri.setLocalIsPK(true);
                ri.setRelatedClass(com.orderdb.Products.class);
                ri.setRelatedAttributes(new String[]{"SupplierID"});
                ri.setRelatedIdentifier("FK:Products[SupplierID]:Suppliers[SupplierID]");
                ri.setLoadMethod("loadProductsObjects");
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public SuppliersBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSupplierID()
    {
        return getIntProperty(ATTR_SupplierID);
    }

    public void setSupplierID(int value)
    {
        setProperty(ATTR_SupplierID, value, 0);
    }

    public String getCompanyName()
    {
        return getStringProperty(ATTR_CompanyName);
    }

    public void setCompanyName(String value)
    {
        setProperty(ATTR_CompanyName, value, 0);
    }

    public String getContactName()
    {
        return getStringProperty(ATTR_ContactName);
    }

    public void setContactName(String value)
    {
        setProperty(ATTR_ContactName, value, 0);
    }

    public String getContactTitle()
    {
        return getStringProperty(ATTR_ContactTitle);
    }

    public void setContactTitle(String value)
    {
        setProperty(ATTR_ContactTitle, value, 0);
    }

    public String getAddress()
    {
        return getStringProperty(ATTR_Address);
    }

    public void setAddress(String value)
    {
        setProperty(ATTR_Address, value, 0);
    }

    public String getCity()
    {
        return getStringProperty(ATTR_City);
    }

    public void setCity(String value)
    {
        setProperty(ATTR_City, value, 0);
    }

    public String getRegion()
    {
        return getStringProperty(ATTR_Region);
    }

    public void setRegion(String value)
    {
        setProperty(ATTR_Region, value, 0);
    }

    public String getPostalCode()
    {
        return getStringProperty(ATTR_PostalCode);
    }

    public void setPostalCode(String value)
    {
        setProperty(ATTR_PostalCode, value, 0);
    }

    public String getCountry()
    {
        return getStringProperty(ATTR_Country);
    }

    public void setCountry(String value)
    {
        setProperty(ATTR_Country, value, 0);
    }

    public String getPhone()
    {
        return getStringProperty(ATTR_Phone);
    }

    public void setPhone(String value)
    {
        setProperty(ATTR_Phone, value, 0);
    }

    public String getFax()
    {
        return getStringProperty(ATTR_Fax);
    }

    public void setFax(String value)
    {
        setProperty(ATTR_Fax, value, 0);
    }

    public String getHomePage()
    {
        return getStringProperty(ATTR_HomePage);
    }

    public void setHomePage(String value)
    {
        setProperty(ATTR_HomePage, value, 0);
    }

    public BusObjectIterator<Products> getProductsObjects()
    {
        return getMultiRelationObjects(REL_ProductsObjects);
    }
    public BusObjectIterator<Products> loadProductsObjects()
    {
        String queryText = "select * from \"Products\" where \"SupplierID\" = :SupplierID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SupplierID", "Products.SupplierID", QueryObject.PARAM_INT, new Integer(getSupplierID()));
        query.setResultClass(Products.class);
        return query.getObjects();
    }


    public void addProductsObject(Products a_Products)
    {
        a_Products.setSupplierID(this.getSupplierID());
    }

    public void removeProductsObject(Products a_Products)
    {
        a_Products.setNull("SupplierID");
    }

    public static BusObjectIterator<com.orderdb.Suppliers> getNextSuppliersObjects(int SupplierID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"Suppliers\" where (\"SupplierID\" > :SupplierID) order by \"SupplierID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(SupplierID));
        query.setResultClass(Suppliers.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.orderdb.Suppliers> getPreviousSuppliersObjects(int SupplierID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"Suppliers\" where (\"SupplierID\" < :SupplierID) order by \"SupplierID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(SupplierID));
        query.setResultClass(Suppliers.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.orderdb.Suppliers getSuppliersObject(int SupplierID)
    {
        String queryText = "select * from \"Suppliers\" where \"SupplierID\" = :SupplierID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(SupplierID));
        query.setResultClass(Suppliers.class);
        return (Suppliers)query.getObject();
    }

    public static BusObjectIterator<com.orderdb.Suppliers> getSuppliersObjects(int fromSupplierID, int toSupplierID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"Suppliers\" where \"SupplierID\" between :fromSupplierID and :toSupplierID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(fromSupplierID));
        query.addParameter("toSupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(toSupplierID));
        query.setResultClass(Suppliers.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.orderdb.Suppliers> getSuppliersObjects(int fromSupplierID, int toSupplierID)
    {
        String queryText = "select * from \"Suppliers\" where \"SupplierID\" between :fromSupplierID and :toSupplierID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(fromSupplierID));
        query.addParameter("toSupplierID", "Suppliers.SupplierID", QueryObject.PARAM_INT, new Integer(toSupplierID));
        query.setResultClass(Suppliers.class);
        return query.getObjects();
    }

}
