/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_FK;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class CustomersBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_CustomerID = "CustomerID";
    public final static String ATTR_CompanyName = "CompanyName";
    public final static String ATTR_ContactName = "ContactName";
    public final static String ATTR_ContactTitle = "ContactTitle";
    public final static String ATTR_Address = "Address";
    public final static String ATTR_City = "City";
    public final static String ATTR_Region = "Region";
    public final static String ATTR_PostalCode = "PostalCode";
    public final static String ATTR_Country = "Country";
    public final static String ATTR_Phone = "Phone";
    public final static String ATTR_Fax = "Fax";
    private final static String REL_CustomerCustomerDemoObjects = "FK:Customers[CustomerID]:CustomerCustomerDemo[CustomerID]";
    private final static String REL_OrdersObjects = "FK:Customers[CustomerID]:Orders[CustomerID]";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(Customers.class);
            s_classInfo.setTableName("Customers");
            s_classInfo.setUIDElements(new String[]{ATTR_CustomerID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CustomerID);
                ai.setJavaName("CustomerID");
                ai.setColumnName("CustomerID");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CustomerID);
                v.setMaxLength(5);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompanyName);
                ai.setJavaName("CompanyName");
                ai.setColumnName("CompanyName");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompanyName);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ContactName);
                ai.setJavaName("ContactName");
                ai.setColumnName("ContactName");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ContactName);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ContactTitle);
                ai.setJavaName("ContactTitle");
                ai.setColumnName("ContactTitle");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ContactTitle);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Address);
                ai.setJavaName("Address");
                ai.setColumnName("Address");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Address);
                v.setMaxLength(60);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_City);
                ai.setJavaName("City");
                ai.setColumnName("City");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_City);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Region);
                ai.setJavaName("Region");
                ai.setColumnName("Region");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Region);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PostalCode);
                ai.setJavaName("PostalCode");
                ai.setColumnName("PostalCode");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PostalCode);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Country);
                ai.setJavaName("Country");
                ai.setColumnName("Country");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Country);
                v.setMaxLength(15);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Phone);
                ai.setJavaName("Phone");
                ai.setColumnName("Phone");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Phone);
                v.setMaxLength(24);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Fax);
                ai.setJavaName("Fax");
                ai.setColumnName("Fax");
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Fax);
                v.setMaxLength(24);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                // relation CustomerCustomerDemoObjects (FK:Customers[CustomerID]:CustomerCustomerDemo[CustomerID])
                RelationInfo_FK ri = new RelationInfo_FK(REL_CustomerCustomerDemoObjects);
                ri.setName("CustomerCustomerDemoObjects");
                ri.setLocalAttributes(new String[]{"CustomerID"});
                ri.setLocalIsPK(true);
                ri.setRelatedClass(com.orderdb.CustomerCustomerDemo.class);
                ri.setRelatedAttributes(new String[]{"CustomerID"});
                ri.setRelatedIdentifier("FK:CustomerCustomerDemo[CustomerID]:Customers[CustomerID]");
                ri.setLoadMethod("loadCustomerCustomerDemoObjects");
                s_classInfo.addRelationInfo(ri);
            }
            {
                // relation OrdersObjects (FK:Customers[CustomerID]:Orders[CustomerID])
                RelationInfo_FK ri = new RelationInfo_FK(REL_OrdersObjects);
                ri.setName("OrdersObjects");
                ri.setLocalAttributes(new String[]{"CustomerID"});
                ri.setLocalIsPK(true);
                ri.setRelatedClass(com.orderdb.Orders.class);
                ri.setRelatedAttributes(new String[]{"CustomerID"});
                ri.setRelatedIdentifier("FK:Orders[CustomerID]:Customers[CustomerID]");
                ri.setLoadMethod("loadOrdersObjects");
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public CustomersBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getCustomerID()
    {
        return getStringProperty(ATTR_CustomerID);
    }

    public void setCustomerID(String value)
    {
        setProperty(ATTR_CustomerID, value, 0);
    }

    public String getCompanyName()
    {
        return getStringProperty(ATTR_CompanyName);
    }

    public void setCompanyName(String value)
    {
        setProperty(ATTR_CompanyName, value, 0);
    }

    public String getContactName()
    {
        return getStringProperty(ATTR_ContactName);
    }

    public void setContactName(String value)
    {
        setProperty(ATTR_ContactName, value, 0);
    }

    public String getContactTitle()
    {
        return getStringProperty(ATTR_ContactTitle);
    }

    public void setContactTitle(String value)
    {
        setProperty(ATTR_ContactTitle, value, 0);
    }

    public String getAddress()
    {
        return getStringProperty(ATTR_Address);
    }

    public void setAddress(String value)
    {
        setProperty(ATTR_Address, value, 0);
    }

    public String getCity()
    {
        return getStringProperty(ATTR_City);
    }

    public void setCity(String value)
    {
        setProperty(ATTR_City, value, 0);
    }

    public String getRegion()
    {
        return getStringProperty(ATTR_Region);
    }

    public void setRegion(String value)
    {
        setProperty(ATTR_Region, value, 0);
    }

    public String getPostalCode()
    {
        return getStringProperty(ATTR_PostalCode);
    }

    public void setPostalCode(String value)
    {
        setProperty(ATTR_PostalCode, value, 0);
    }

    public String getCountry()
    {
        return getStringProperty(ATTR_Country);
    }

    public void setCountry(String value)
    {
        setProperty(ATTR_Country, value, 0);
    }

    public String getPhone()
    {
        return getStringProperty(ATTR_Phone);
    }

    public void setPhone(String value)
    {
        setProperty(ATTR_Phone, value, 0);
    }

    public String getFax()
    {
        return getStringProperty(ATTR_Fax);
    }

    public void setFax(String value)
    {
        setProperty(ATTR_Fax, value, 0);
    }

    public BusObjectIterator<CustomerCustomerDemo> getCustomerCustomerDemoObjects()
    {
        return getMultiRelationObjects(REL_CustomerCustomerDemoObjects);
    }
    public BusObjectIterator<CustomerCustomerDemo> loadCustomerCustomerDemoObjects()
    {
        String queryText = "select * from \"CustomerCustomerDemo\" where \"CustomerID\" = :CustomerID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CustomerID", "CustomerCustomerDemo.CustomerID", QueryObject.PARAM_STRING, getCustomerID());
        query.setResultClass(CustomerCustomerDemo.class);
        return query.getObjects();
    }


    public void addCustomerCustomerDemoObject(CustomerCustomerDemo a_CustomerCustomerDemo)
    {
        a_CustomerCustomerDemo.setCustomerID(this.getCustomerID());
    }

    public void removeCustomerCustomerDemoObject(CustomerCustomerDemo a_CustomerCustomerDemo)
    {
        a_CustomerCustomerDemo.setNull("CustomerID");
    }

    public BusObjectIterator<Orders> getOrdersObjects()
    {
        return getMultiRelationObjects(REL_OrdersObjects);
    }
    public BusObjectIterator<Orders> loadOrdersObjects()
    {
        String queryText = "select * from \"Orders\" where \"CustomerID\" = :CustomerID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CustomerID", "Orders.CustomerID", QueryObject.PARAM_STRING, getCustomerID());
        query.setResultClass(Orders.class);
        return query.getObjects();
    }


    public void addOrdersObject(Orders a_Orders)
    {
        a_Orders.setCustomerID(this.getCustomerID());
    }

    public void removeOrdersObject(Orders a_Orders)
    {
        a_Orders.setNull("CustomerID");
    }

    public static com.orderdb.Customers getCustomersObject(String CustomerID)
    {
        String queryText = "select * from \"Customers\" where \"CustomerID\" = :CustomerID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, CustomerID);
        query.setResultClass(Customers.class);
        return (Customers)query.getObject();
    }

    public static BusObjectIterator<com.orderdb.Customers> getCustomersObjects(String fromCustomerID, String toCustomerID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"Customers\" where \"CustomerID\" between :fromCustomerID and :toCustomerID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, fromCustomerID);
        query.addParameter("toCustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, toCustomerID);
        query.setResultClass(Customers.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.orderdb.Customers> getCustomersObjects(String fromCustomerID, String toCustomerID)
    {
        String queryText = "select * from \"Customers\" where \"CustomerID\" between :fromCustomerID and :toCustomerID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, fromCustomerID);
        query.addParameter("toCustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, toCustomerID);
        query.setResultClass(Customers.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.orderdb.Customers> getNextCustomersObjects(String CustomerID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"Customers\" where (\"CustomerID\" > :CustomerID) order by \"CustomerID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, CustomerID);
        query.setResultClass(Customers.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.orderdb.Customers> getPreviousCustomersObjects(String CustomerID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"Customers\" where (\"CustomerID\" < :CustomerID) order by \"CustomerID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("CustomerID", "Customers.CustomerID", QueryObject.PARAM_STRING, CustomerID);
        query.setResultClass(Customers.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
