/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Customers extends CustomersBase
{
    public Customers()
    {
        this((BusObjectConfig)null);
    }

    public Customers(BusObjectConfig config)
    {
        super(config);
    }

}
