/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Products extends ProductsBase
{
    public Products()
    {
        this((BusObjectConfig)null);
    }

    public Products(BusObjectConfig config)
    {
        super(config);
    }

}
