/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Shippers extends ShippersBase
{
    public Shippers()
    {
        this((BusObjectConfig)null);
    }

    public Shippers(BusObjectConfig config)
    {
        super(config);
    }

}
