/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Suppliers extends SuppliersBase
{
    public Suppliers()
    {
        this((BusObjectConfig)null);
    }

    public Suppliers(BusObjectConfig config)
    {
        super(config);
    }

}
