/*
  This class has been generated by the Code Generator
*/

package com.orderdb;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Territories extends TerritoriesBase
{
    public Territories()
    {
        this((BusObjectConfig)null);
    }

    public Territories(BusObjectConfig config)
    {
        super(config);
    }

}
